# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Xpriori-XMS
version:      0.01
version_from: lib/Xpriori/XMS/Http.pm
installdirs:  site
requires:
    Digest::MD5:                   
    HTTP::Request:                 
    LWP:                           
    URI::Escape:                   
    Win32::Service:                

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
